# Generated by Django 3.2.4 on 2021-07-02 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_auto_20210702_0247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
